from selenium import webdriver
from time import sleep

'''
for i in range(3):
    driver = webdriver.Chrome()
    driver2 = webdriver.Chrome()
    driver3 = webdriver.Chrome()
    driver.get('https://hours.zone')
    driver2.get('https://hours.zone')
    driver3.get('https://hours.zone')
    driver.find_element_by_xpath('//*[@id="__next"]/header/div/div/a').click()
    driver2.find_element_by_xpath('//*[@id="__next"]/header/div/div/a').click()
    driver3.find_element_by_xpath('//*[@id="__next"]/header/div/div/a').click()
    session_title = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[1]/input')
    session_title2 = driver2.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[1]/input')
    session_title3 = driver3.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[1]/input')
    session_title.send_keys('Test')
    session_title2.send_keys('Test')
    session_title3.send_keys('Test')
    name = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[2]/input')
    name2 = driver2.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[2]/input')
    name3 = driver3.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[2]/input')
    name.send_keys('Testing')
    name2.send_keys('Testing')
    name3.send_keys('Testing')
    driver.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[3]/button').click()
    driver2.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[3]/button').click()
    driver3.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[3]/button').click()
    sleep(1)
    print(driver.current_url)
    print(driver2.current_url)
    print(driver3.current_url)
    driver.close()
    driver2.close()
    driver3.close()
'''

for i in range(100):
    driver = webdriver.Chrome()
    driver.get('https://hours.zone')
    driver.find_element_by_xpath('//*[@id="__next"]/header/div/div/a').click()
    session_title = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[1]/input')
    session_title.send_keys('Test')
    name = driver.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[2]/input')
    name.send_keys('Testing')
    driver.find_element_by_xpath('//*[@id="__next"]/div[1]/div/div[3]/button').click()
    sleep(1)
    print(driver.current_url)
    driver.close()
